In [1]:
import pandas as pd
df = pd.read_json("competitions.json")
df.head()

c:\Users\Liuhy\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\Liuhy\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In this section, I will use the dataset to find the specific data of a single season. For example, we want find the 2018/2019 season La Liga Matches.

In [2]:
index_league = "La Liga" 
index_season = "2015/2016"

In [3]:
Match_data =df.loc[(df["competition_name"] == index_league) & (df["season_name"] == index_season),
                    ["competition_id", "season_id","competition_name", "season_name", ]]
Match_data
COMPETITION_ID = Match_data["competition_id"].values[0]
SEASON_ID = Match_data["season_id"].values[0]

Now we find all the matches in La Liga in 2018/2019 season. Let's first take a look at the constructure of its correspondent match.json.

In [4]:

from pathlib import Path
DATA_DIR = Path("D:/UIUC/Projects/World Cup 2026/archive/data")
match_file = DATA_DIR / "matches"/str(COMPETITION_ID) / f"{SEASON_ID}.json"
df_match = pd.read_json(match_file)
df_match.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,3825739,2016-01-17,17:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 220, 'home_team_name': 'Real ...","{'away_team_id': 1041, 'away_team_name': 'Spor...",5,1,available,unscheduled,2024-05-16T14:06:52.149840,NaN,"{'data_version': '1.1.0', 'shot_fidelity_versi...",20,"{'id': 1, 'name': 'Regular Season'}","{'id': 353, 'name': 'Bernabéu', 'country': {'i...","{'id': 221, 'name': 'Alberto Undiano Mallenco'..."
1,3825848,2015-09-23,20:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 221, 'home_team_name': 'Levan...","{'away_team_id': 322, 'away_team_name': 'Eibar...",2,2,available,unscheduled,2024-08-23T09:35:15.821559,NaN,"{'data_version': '1.1.0', 'shot_fidelity_versi...",5,"{'id': 1, 'name': 'Regular Season'}","{'id': 350, 'name': 'Estadio Ciudad de Valenci...",NaN
2,3825895,2015-09-23,22:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 208, 'home_team_name': 'Las P...","{'away_team_id': 213, 'away_team_name': 'Sevil...",2,0,available,unscheduled,2023-02-21T15:19:07.927548,NaN,"{'data_version': '1.1.0', 'shot_fidelity_versi...",5,"{'id': 1, 'name': 'Regular Season'}","{'id': 357, 'name': 'Estadio de Gran Canaria',...","{'id': 2728, 'name': 'Carlos del Cerro Grande'..."
3,3825894,2016-05-01,18:15:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 219, 'home_team_name': 'RC De...","{'away_team_id': 216, 'away_team_name': 'Getaf...",0,2,available,unscheduled,2022-08-30T12:53:16.828350,NaN,"{'data_version': '1.1.0', 'shot_fidelity_versi...",36,"{'id': 1, 'name': 'Regular Season'}","{'id': 4658, 'name': 'Estadio Abanca-Riazor', ...","{'id': 1008, 'name': 'Carlos Clos Gómez', 'cou..."
4,3825855,2016-05-02,20:30:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 223, 'home_team_name': 'Málag...","{'away_team_id': 221, 'away_team_name': 'Levan...",3,1,available,unscheduled,2022-08-30T12:53:53.790835,NaN,"{'data_version': '1.1.0', 'shot_fidelity_versi...",36,"{'id': 1, 'name': 'Regular Season'}","{'id': 346, 'name': 'Estadio La Rosaleda', 'co...","{'id': 2480, 'name': 'Iñaki Bikandi Garrido', ..."

We noticed that there are many dictionary under the column like the home_team and away_team. I want to normalize this dataframe and make it looks better.

In [5]:
from pandas import json_normalize
# Split the "home_team" dictionary into multiple columns and concatenate them with the original df.
df_home = df_match['home_team'].apply(pd.Series)
df_home = df_home.rename(columns={
    "home_team_id":"home_team_id",
    "home_team_name":"home_team_name"
})
# away_team同理
df_away = df_match['away_team'].apply(pd.Series)
df_away = df_away.rename(columns={
    "away_team_id":"away_team_id",
    "away_team_name":"away_team_name"
})
# 合并回原表，可按需删除原来的字典列
df_match = pd.concat([df_match, df_home, df_away], axis=1)
# 如果不需要原始字典列，可执行：df.drop(columns=["home_team","away_team"],inplace=True)

The second way that using json_normalize the dictionary.

from pandas import json_normalize
    展开主场队伍字段
home_norm = json_normalize(df_match['home_team'])
away_norm = json_normalize(df_match['away_team'])

horizontally concatenate the normalized dataframes with the original dataframe
df_match = pd.concat([df_match, home_norm, away_norm], axis=1)
df_match.head()

Now I want to find out all the Barcelona's matches, no matter it's home or away. Actually, I realized that I no need to expand the dictionary. We can use .str[] to read the internal field.

In [6]:
#  Barcelona
mask = (
    (df_match["home_team"].str["home_team_name"] == "Barcelona")
    |
    (df_match["away_team"].str["away_team_name"] == "Barcelona")
)
barca_matches = df_match.loc[mask]

In [7]:
mask = (
    (df_match["home_team_name"] == "Real Madrid")
    |
    (df_match["away_team_name"] == "Real Madrid")
)
realmadrid_matches = df_match.loc[mask]
len(barca_matches), len(realmadrid_matches)

(38, 38)

In [8]:
barca_matches.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'metadata',
       'match_week', 'competition_stage', 'stadium', 'referee', 'home_team_id',
       'home_team_name', 'home_team_gender', 'home_team_group', 'country',
       'managers', 'away_team_id', 'away_team_name', 'away_team_gender',
       'away_team_group', 'country', 'managers'],
      dtype='str')

In [9]:

barca_matches = barca_matches.sort_values(by='match_date', ascending=True)
barca_matches[['match_id','match_date','home_team_name','away_team_name','home_score','away_score','competition_stage'
        ]].head(10)

,match_id,match_date,home_team_name,away_team_name,home_score,away_score,competition_stage
358,266236,2015-08-23,Athletic Club,Barcelona,0,1,"{'id': 1, 'name': 'Regular Season'}"
357,267422,2015-08-29,Barcelona,Málaga,1,0,"{'id': 1, 'name': 'Regular Season'}"
371,266166,2015-09-12,Atlético Madrid,Barcelona,1,2,"{'id': 1, 'name': 'Regular Season'}"
377,266490,2015-09-20,Barcelona,Levante UD,4,1,"{'id': 1, 'name': 'Regular Season'}"
375,266467,2015-09-23,Celta Vigo,Barcelona,4,1,"{'id': 1, 'name': 'Regular Season'}"
356,267611,2015-09-26,Barcelona,Las Palmas,2,1,"{'id': 1, 'name': 'Regular Season'}"
306,3825617,2015-10-03,Sevilla,Barcelona,2,1,"{'id': 1, 'name': 'Regular Season'}"
300,3825627,2015-10-17,Barcelona,Rayo Vallecano,5,2,"{'id': 1, 'name': 'Regular Season'}"
186,3825637,2015-10-25,Barcelona,Eibar,3,1,"{'id': 1, 'name': 'Regular Season'}"
288,3825645,2015-10-31,Getafe,Barcelona,0,2,"{'id': 1, 'name': 'Regular Season'}"

First, we do a seasonal analysis. These data could be very easy to get if you open any football website. Like what's the ranking of the team and what is the total goals of this team in this single season

In [10]:
def get_barca_res(row):
    if row["home_team_name"] =="Barcelona":
        barcelona_score = row["home_score"]
        opponent_score = row["away_score"]
    else:
        barcelona_score = row["away_score"]
        opponent_score = row["home_score"]  
    if barcelona_score > opponent_score:
        return "Win"    
    if barcelona_score < opponent_score:
        return "Lose"
    if barcelona_score == opponent_score:
        return "Draw"

barca_matches["barca_result"] = barca_matches.apply(get_barca_res, axis=1)
 #add a new column summarize the result of Barcelona

result_counts = barca_matches["barca_result"].value_counts()
win_count = result_counts.get("Win", 0)
lose_count = result_counts.get("Lose", 0)   
draw_count = result_counts.get("Draw", 0)

#calculate the total credit points for Barcelona based on the results
total_points = win_count * 3 + draw_count * 1 + lose_count * 0

print(f"Barcelona's total points in {index_season} season {index_league}: {total_points}")

Barcelona's total points in 2015/2016 season La Liga: 91

Now we can count the total goals and the total conceded goals of a team in one season. And the average data.

In [11]:
def goals(row):
    if row["home_team_name"] =="Barcelona":
        barcelona_score = row["home_score"]
        opponent_score = row["away_score"]
    else:
        barcelona_score = row["away_score"]
        opponent_score = row["home_score"]  
    return barcelona_score, opponent_score

barca_matches[["barca_goals","opponent_goals"]] = barca_matches.apply(goals, axis=1, result_type="expand")

total_goals_scored = barca_matches["barca_goals"].sum()
total_goals_conceded = barca_matches["opponent_goals"].sum()
print(f"Barcelona's total goals scored in {index_season} season {index_league}: {total_goals_scored}")
print(f"Barcelona's total goals conceded in {index_season} season {index_league}: {total_goals_conceded}")

#The average goals scored and conceded per match
average_goals_scored = total_goals_scored / len(barca_matches)
average_goals_conceded = total_goals_conceded / len(barca_matches)
print(f"Barcelona's average goals scored per match in {index_season} season {index_league}: {average_goals_scored:.2f}")
print(f"Barcelona's average goals conceded per match in {index_season} season {index_league}: {average_goals_conceded:.2f}")

Barcelona's total goals scored in 2015/2016 season La Liga: 112
Barcelona's total goals conceded in 2015/2016 season La Liga: 29
Barcelona's average goals scored per match in 2015/2016 season La Liga: 2.95
Barcelona's average goals conceded per match in 2015/2016 season La Liga: 0.76

Despite of single team's performance. We can make a brief statistic description of this league. Here I rank the points of each team and the goal difference.

In [12]:
df_match.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,home_team_gender,home_team_group,country,managers,away_team_id,away_team_name,away_team_gender,away_team_group,country,managers
0,3825739,2016-01-17,17:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 220, 'home_team_name': 'Real ...","{'away_team_id': 1041, 'away_team_name': 'Spor...",5,1,available,...,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 56, 'name': 'Zinédine Zidane', 'nickna...",1041,Sporting Gijón,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 187, 'name': 'Abelardo Fernández Antuñ..."
1,3825848,2015-09-23,20:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 221, 'home_team_name': 'Levan...","{'away_team_id': 322, 'away_team_name': 'Eibar...",2,2,available,...,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 1612, 'name': 'Luis Lucas Alcaraz Gonz...",322,Eibar,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 221, 'name': 'José Luis Mendilibar Etx..."
2,3825895,2015-09-23,22:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 208, 'home_team_name': 'Las P...","{'away_team_id': 213, 'away_team_name': 'Sevil...",2,0,available,...,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 745, 'name': 'Francisco Herrera Lorenz...",213,Sevilla,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 21, 'name': 'Unai Emery Etxegoien', 'n..."
3,3825894,2016-05-01,18:15:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 219, 'home_team_name': 'RC De...","{'away_team_id': 216, 'away_team_name': 'Getaf...",0,2,available,...,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 3157, 'name': 'Víctor Sánchez del Amo'...",216,Getafe,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 1001036, 'name': 'Juan Eduardo Esnáide..."
4,3825855,2016-05-02,20:30:00.000,"{'competition_id': 11, 'country_name': 'Spain'...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 223, 'home_team_name': 'Málag...","{'away_team_id': 221, 'away_team_name': 'Levan...",3,1,available,...,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 188, 'name': 'Javier Gracia Carlos', '...",221,Levante UD,male,None,"{'id': 214, 'name': 'Spain'}","[{'id': 677, 'name': 'Joan Francesc Ferrer Sic..."

In [13]:
len(df_match)

380

In [ ]:
def split_match(row):
    #home team records:
    home_goals = row["home_score"]
    away_goals = row["away_score"]
    if home_goals > away_goals:
        home_pts = 3
        away_pts = 0
    elif home_goals == away_goals:#the second condition should be used elif, or the the first condition is ignored.
        home_pts = 1
        away_pts = 1
    else:
        home_pts = 0
        away_pts = 3

    home_row = {'team': row["home_team_name"], 'goals_scored': home_goals, 'goals_conceded': away_goals, 'points': home_pts}
    away_row = {'team': row["away_team_name"], 'goals_scored': away_goals, 'goals_conceded': home_goals, 'points': away_pts}
    return [home_row, away_row]

match_list = []#create an empty list to store the match data for each team
for index, row in df_match.iterrows():
    #iterrows() is used to iterate over the rows of the DataFrame, returning both the index and the row data as a Series.
    match_list.extend(split_match(row))
team_df = pd.DataFrame(match_list)

team_df.head()

             team  goals_scored  goals_conceded  points
0     Real Madrid             5               1       3
1  Sporting Gijón             1               5       0
2      Levante UD             2               2       1
3           Eibar             2               2       1
4      Las Palmas             2               0       3

In [24]:
league_table = team_df.groupby("team", as_index=False).agg(
    total_scored = ('goals_scored', 'sum'),
    total_conceded = ('goals_conceded', 'sum'), 
    total_points = ('points', 'sum')
)
league_table = league_table.sort_values(by='total_points', ascending=False)
league_table['goals_difference'] = league_table['total_scored']-league_table['total_conceded']
league_table['average_goals_scored'] = league_table['total_scored']/38
league_table.head(20)

,team,total_scored,total_conceded,total_points,goals_difference,average_goals_scored
2,Barcelona,112,29,91,83,2.947368
14,Real Madrid,110,34,90,76,2.894737
1,Atlético Madrid,63,18,88,45,1.657895
19,Villarreal,44,35,64,9,1.157895
0,Athletic Club,58,45,62,13,1.526316
3,Celta Vigo,51,59,60,-8,1.342105
16,Sevilla,51,50,52,1,1.342105
15,Real Sociedad,45,48,48,-3,1.184211
10,Málaga,38,35,48,3,1.000000
13,Real Betis,34,52,45,-18,0.894737
8,Las Palmas,45,53,44,-8,1.184211
18,Valencia,46,48,44,-2,1.210526
5,Espanyol,40,74,43,-34,1.052632
4,Eibar,49,61,43,-12,1.289474
11,RC Deportivo La Coruña,45,61,42,-16,1.184211
7,Granada,46,69,39,-23,1.210526
17,Sporting Gijón,40,62,39,-22,1.052632
12,Rayo Vallecano,52,73,38,-21,1.368421
6,Getafe,37,67,36,-30,0.973684
9,Levante UD,37,70,32,-33,0.973684

In [16]:
event_file = DATA_DIR / "events" / f"{barca_matches['match_id'].values[0]}.json"